theme: minima
title: Let's connect and share
author: Arpit Gupta 
email: gupta.arpit03@gmail.com  
description: > # this means to ignore newlines until "baseurl:"
  Let's connect and share our work with each other.

# social links
twitter_username: arpitram3 # DO NOT include the @ character, or else the build will fail!
github_username:  imarg3 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
